# servicemonitor resource
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hitcounter-app-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: flask-app
  namespaceSelector:
    any: true
  endpoints:
    port: web
    path: /metrics
