version: '3'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      REDIS_USERNAME: default
      REDIS_PASSWORD: KKsAO31VMFKdfwnw5INH2vfKQkyqlUCV
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
