global:
  scrape_interval: 15s  # Set the scrape interval to every 15 seconds. Default is every 1 minute.

scrape_configs:
  - job_name: 'kubernetes-services'
    kubernetes_sd_configs:
      - role: service
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        regex: hitcounter_app
        action: keep
    metrics_path: '/metrics'
    scheme: 'http'






